### ISSUE TITLE
How to make it work on a Docker Container ?

### ISSUE THREAD

**Issue by nestarz** [bcongdon/bpy_lambda#5]
Hi,

I have this error when doing an import of bpy_lambda:
`OSError: libGL.so.1: cannot open shared object file: No such file or directory
`
I run python on a linux docker container.

Thanks,

**Comment by bcongdon** [comment]
Which docker image are you basing it on? That error looks like you're missing a dependency.

If you just want to get this working in docker, you can use the [`lambci/lambda` docker image](https://hub.docker.com/r/lambci/lambda/), which replicates Lambda's environment:

```
docker run -it lambci/lambda:build-python3.6 bash
bash-4.2# pip install bpy_lambda
...
bash-4.2# python
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bpy_lambda import bpy
...
>>> 
```

**Comment by nestarz** [comment]
First, thanks so much for your answer only 10min after !
I use this docker image: https://hub.docker.com/r/ufoym/deepo/

I can't use any docker image with python and pip ?

Thanks,
Elias

**Comment by bcongdon** [comment]
You should be able to use any docker image with python/pip, but you may have to install some system libraries before you can use it.

I was able to get bpy_lambda to work on that image by installing `libgl1-mesa-glx` and `libjpeg62`

i.e. running this allowed bpy_lambda to work:
```
apt-get update
apt-get install libgl1-mesa-glx libjpeg62
```
