### ISSUE TITLE
Docker image missing dependencies

### ISSUE THREAD

**Issue by emlyn-Resn** [bcongdon/bpy_lambda#7]
I'm trying to build bpy using the supplied [Docker image](https://github.com/bcongdon/bpy_lambda/blob/9b6cb4a07a7619315889b119f2c40feaff3c7c37/docker/Dockerfile), but it looks like it's missing some dependencies now.

```
No package python36 available.
No package python36-devel available.
No package python36-libs available.
No package freealut-devel available.
No package jack-audio-connection-kit-devel available.
No package xvidcore-devel available.
No package faac-devel available.
No package faad2-devel available.
No package x264-devel available.
```

The python3 module is based on 3.7 now, but even when I swap those out, I couldn't find replacements for some of the others.  Do you know what tag this was originally built against?

I can install the version you've got uploaded to pip, but i'm wanting to compile a version with some extra features.

Thanks for your project though. I had been struggling to get Blender compiled against amazonlinux, so it has been a great help.

**Comment by bcongdon** [comment]
Thanks for the bug report. I updated the Dockerfile to be tagged against the 2017 version of amazonlinux, and now we install python from source instead of using the RPM package.

You can see more details in #10. Hopefully this fixes this issue. 🙂

**Comment by emlyn-Resn** [comment]
Awesome, thanks.  Seems to be compiling with no issues now 🥇
